In [35]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [36]:
df = pd.read_csv('data/fruits_train.csv')
df

,vitamin A %,vitamin C %,calcium %,iron %,magnesium %,calories (per 100g),potassium (mg),protein (g),fiber (g),classification
0,1.0,7.0,0.0,0.0,1.0,52.0,107.0,0.3,2.4,fruit
1,38.0,16.0,1.0,2.0,2.0,48.0,259.0,1.4,2.0,fruit
2,2.0,16.0,1.0,3.0,7.0,160.0,485.0,2.0,7.0,fruit
3,1.0,14.0,0.0,1.0,6.0,89.0,358.0,1.1,2.6,fruit
4,0.0,8.0,1.0,1.0,5.0,43.0,325.0,1.6,2.8,vegetable
5,4.0,35.0,2.0,3.0,5.0,43.0,163.0,1.4,5.0,fruit
6,1.0,16.0,0.0,1.0,1.0,57.0,77.0,0.7,2.4,fruit
7,12.0,148.0,4.0,3.0,5.0,34.0,316.0,2.8,2.6,vegetable
8,15.0,141.0,4.0,7.0,5.0,43.0,389.0,3.4,3.8,vegetable
9,334.0,9.0,3.0,1.0,3.0,41.0,320.0,0.9,2.8,vegetable
10,0.0,80.0,2.0,2.0,3.0,25.0,299.0,1.9,2.0,vegetable
11,8.0,5.0,4.0,1.0,2.0,16.0,260.0,0.7,1.6,vegetable
12,26.0,16.0,1.0,1.0,2.0,50.0,173.0,1.0,1.6,fruit
13,2.0,4.0,1.0,1.0,3.0,16.0,147.0,0.7,0.5,vegetable
14,0.0,3.0,0.0,1.0,3.0,25.0,229.0,1.0,3.0,vegetable
15,12.0,60.0,3.0,8.0,1.0,73.0,280.0,0.7,7.0,fruit
16,2.0,6.0,1.0,1.0,1.0,67.0,191.0,0.6,0.9,fruit
17,33.0,20.0,5.0,11.0,7.0,61.0,180.0,1.5,1.8,vegetable
18,0.0,88.0,2.0,3.0,2.0,29.0,138.0,1.1,2.8,fruit
19,21.0,60.0,1.0,1.0,2.0,60.0,168.0,0.8,1.6,fruit
20,4.0,88.0,4.0,0.0,2.0,47.0,181.0,0.9,2.4,fruit
21,1.0,79.0,1.0,1.0,3.0,50.0,109.0,0.5,1.4,fruit
22,6.0,11.0,0.0,1.0,2.0,39.0,190.0,0.9,1.5,fruit
23,0.0,7.0,0.0,1.0,1.0,57.0,116.0,0.4,3.1,fruit
24,7.0,134.0,1.0,1.0,2.0,20.0,175.0,0.9,1.7,vegetable
25,6.0,15.0,0.0,1.0,1.0,46.0,157.0,0.7,1.4,fruit
26,0.0,17.0,1.0,1.0,3.0,83.0,236.0,1.7,4.0,fruit
27,170.0,15.0,2.0,4.0,3.0,26.0,340.0,1.0,0.5,vegetable
28,187.0,46.0,9.0,15.0,19.0,23.0,558.0,2.9,2.2,vegetable
29,0.0,97.0,1.0,2.0,3.0,33.0,153.0,0.7,2.0,fruit
30,283.0,4.0,3.0,3.0,6.0,86.0,337.0,1.6,3.0,vegetable
31,13.0,44.0,3.0,1.0,3.0,53.0,166.0,0.8,1.8,fruit
32,16.0,22.0,1.0,1.0,2.0,18.0,237.0,0.9,1.2,fruit
33,11.0,13.0,0.0,1.0,2.0,30.0,112.0,0.6,0.4,vegetable
34,4.0,29.0,1.0,2.0,4.0,17.0,261.0,1.2,1.0,vegetable

In [37]:
x = df.iloc[:, :-1] # site koloni osven poslednata
y = df['classification']

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=98, test_size=0.30) #25% od podatocite ke se za test

In [39]:
x_train

,vitamin A %,vitamin C %,calcium %,iron %,magnesium %,calories (per 100g),potassium (mg),protein (g),fiber (g)
20,4.0,88.0,4.0,0.0,2.0,47.0,181.0,0.9,2.4
19,21.0,60.0,1.0,1.0,2.0,60.0,168.0,0.8,1.6
17,33.0,20.0,5.0,11.0,7.0,61.0,180.0,1.5,1.8
28,187.0,46.0,9.0,15.0,19.0,23.0,558.0,2.9,2.2
30,283.0,4.0,3.0,3.0,6.0,86.0,337.0,1.6,3.0
29,0.0,97.0,1.0,2.0,3.0,33.0,153.0,0.7,2.0
15,12.0,60.0,3.0,8.0,1.0,73.0,280.0,0.7,7.0
3,1.0,14.0,0.0,1.0,6.0,89.0,358.0,1.1,2.6
22,6.0,11.0,0.0,1.0,2.0,39.0,190.0,0.9,1.5
24,7.0,134.0,1.0,1.0,2.0,20.0,175.0,0.9,1.7
21,1.0,79.0,1.0,1.0,3.0,50.0,109.0,0.5,1.4
32,16.0,22.0,1.0,1.0,2.0,18.0,237.0,0.9,1.2
33,11.0,13.0,0.0,1.0,2.0,30.0,112.0,0.6,0.4
34,4.0,29.0,1.0,2.0,4.0,17.0,261.0,1.2,1.0
23,0.0,7.0,0.0,1.0,1.0,57.0,116.0,0.4,3.1
2,2.0,16.0,1.0,3.0,7.0,160.0,485.0,2.0,7.0
9,334.0,9.0,3.0,1.0,3.0,41.0,320.0,0.9,2.8
6,1.0,16.0,0.0,1.0,1.0,57.0,77.0,0.7,2.4
7,12.0,148.0,4.0,3.0,5.0,34.0,316.0,2.8,2.6
4,0.0,8.0,1.0,1.0,5.0,43.0,325.0,1.6,2.8
1,38.0,16.0,1.0,2.0,2.0,48.0,259.0,1.4,2.0
25,6.0,15.0,0.0,1.0,1.0,46.0,157.0,0.7,1.4
27,170.0,15.0,2.0,4.0,3.0,26.0,340.0,1.0,0.5
26,0.0,17.0,1.0,1.0,3.0,83.0,236.0,1.7,4.0

In [40]:
x_test

,vitamin A %,vitamin C %,calcium %,iron %,magnesium %,calories (per 100g),potassium (mg),protein (g),fiber (g)
13,2.0,4.0,1.0,1.0,3.0,16.0,147.0,0.7,0.5
31,13.0,44.0,3.0,1.0,3.0,53.0,166.0,0.8,1.8
18,0.0,88.0,2.0,3.0,2.0,29.0,138.0,1.1,2.8
16,2.0,6.0,1.0,1.0,1.0,67.0,191.0,0.6,0.9
0,1.0,7.0,0.0,0.0,1.0,52.0,107.0,0.3,2.4
11,8.0,5.0,4.0,1.0,2.0,16.0,260.0,0.7,1.6
10,0.0,80.0,2.0,2.0,3.0,25.0,299.0,1.9,2.0
8,15.0,141.0,4.0,7.0,5.0,43.0,389.0,3.4,3.8
5,4.0,35.0,2.0,3.0,5.0,43.0,163.0,1.4,5.0
12,26.0,16.0,1.0,1.0,2.0,50.0,173.0,1.0,1.6
14,0.0,3.0,0.0,1.0,3.0,25.0,229.0,1.0,3.0

In [41]:
y_train

20        fruit
19        fruit
17    vegetable
28    vegetable
30    vegetable
29        fruit
15        fruit
3         fruit
22        fruit
24    vegetable
21        fruit
32        fruit
33    vegetable
34    vegetable
23        fruit
2         fruit
9     vegetable
6         fruit
7     vegetable
4     vegetable
1         fruit
25        fruit
27    vegetable
26        fruit
Name: classification, dtype: object

In [42]:
y_test

13    vegetable
31        fruit
18        fruit
16        fruit
0         fruit
11    vegetable
10    vegetable
8     vegetable
5         fruit
12        fruit
14    vegetable
Name: classification, dtype: object

In [43]:
clf = DecisionTreeClassifier(criterion = 'entropy') ##vogalvno jas odbrav za entropy a ne gini, gini e poleso za kompjuterot ne presmetuva log postojano
clf

DecisionTreeClassifier(criterion='entropy')

In [44]:
clf.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [46]:
y_pred = clf.predict(x_test)

In [47]:
print('Accuracy Score on train data: ', accuracy_score(y_true=y_train, y_pred=clf.predict(x_train)))
print('Accuracy Score on test data: ', accuracy_score(y_true=y_test, y_pred=y_pred))

Accuracy Score on train data:  1.0
Accuracy Score on test data:  0.7272727272727273

In [48]:
## ova znaci deka modelot gi pamti sovrseno (1 sto znaci 100%), dodeka pak od test primerite pogodil okolu 73%

Кои производи алгоритамот успева да ги распознава подобро, висококалоричните (над 50 калории) или нискокалоричните (под 50 калории)?

In [52]:
df_high_cal = df[df['calories (per 100g)']>=50]
df_low_cal = df[df['calories (per 100g)']<50]
df_low_cal

,vitamin A %,vitamin C %,calcium %,iron %,magnesium %,calories (per 100g),potassium (mg),protein (g),fiber (g),classification
1,38.0,16.0,1.0,2.0,2.0,48.0,259.0,1.4,2.0,fruit
4,0.0,8.0,1.0,1.0,5.0,43.0,325.0,1.6,2.8,vegetable
5,4.0,35.0,2.0,3.0,5.0,43.0,163.0,1.4,5.0,fruit
7,12.0,148.0,4.0,3.0,5.0,34.0,316.0,2.8,2.6,vegetable
8,15.0,141.0,4.0,7.0,5.0,43.0,389.0,3.4,3.8,vegetable
9,334.0,9.0,3.0,1.0,3.0,41.0,320.0,0.9,2.8,vegetable
10,0.0,80.0,2.0,2.0,3.0,25.0,299.0,1.9,2.0,vegetable
11,8.0,5.0,4.0,1.0,2.0,16.0,260.0,0.7,1.6,vegetable
13,2.0,4.0,1.0,1.0,3.0,16.0,147.0,0.7,0.5,vegetable
14,0.0,3.0,0.0,1.0,3.0,25.0,229.0,1.0,3.0,vegetable
18,0.0,88.0,2.0,3.0,2.0,29.0,138.0,1.1,2.8,fruit
20,4.0,88.0,4.0,0.0,2.0,47.0,181.0,0.9,2.4,fruit
22,6.0,11.0,0.0,1.0,2.0,39.0,190.0,0.9,1.5,fruit
24,7.0,134.0,1.0,1.0,2.0,20.0,175.0,0.9,1.7,vegetable
25,6.0,15.0,0.0,1.0,1.0,46.0,157.0,0.7,1.4,fruit
27,170.0,15.0,2.0,4.0,3.0,26.0,340.0,1.0,0.5,vegetable
28,187.0,46.0,9.0,15.0,19.0,23.0,558.0,2.9,2.2,vegetable
29,0.0,97.0,1.0,2.0,3.0,33.0,153.0,0.7,2.0,fruit
32,16.0,22.0,1.0,1.0,2.0,18.0,237.0,0.9,1.2,fruit
33,11.0,13.0,0.0,1.0,2.0,30.0,112.0,0.6,0.4,vegetable
34,4.0,29.0,1.0,2.0,4.0,17.0,261.0,1.2,1.0,vegetable

In [53]:
df_high_cal

,vitamin A %,vitamin C %,calcium %,iron %,magnesium %,calories (per 100g),potassium (mg),protein (g),fiber (g),classification
0,1.0,7.0,0.0,0.0,1.0,52.0,107.0,0.3,2.4,fruit
2,2.0,16.0,1.0,3.0,7.0,160.0,485.0,2.0,7.0,fruit
3,1.0,14.0,0.0,1.0,6.0,89.0,358.0,1.1,2.6,fruit
6,1.0,16.0,0.0,1.0,1.0,57.0,77.0,0.7,2.4,fruit
12,26.0,16.0,1.0,1.0,2.0,50.0,173.0,1.0,1.6,fruit
15,12.0,60.0,3.0,8.0,1.0,73.0,280.0,0.7,7.0,fruit
16,2.0,6.0,1.0,1.0,1.0,67.0,191.0,0.6,0.9,fruit
17,33.0,20.0,5.0,11.0,7.0,61.0,180.0,1.5,1.8,vegetable
19,21.0,60.0,1.0,1.0,2.0,60.0,168.0,0.8,1.6,fruit
21,1.0,79.0,1.0,1.0,3.0,50.0,109.0,0.5,1.4,fruit
23,0.0,7.0,0.0,1.0,1.0,57.0,116.0,0.4,3.1,fruit
26,0.0,17.0,1.0,1.0,3.0,83.0,236.0,1.7,4.0,fruit
30,283.0,4.0,3.0,3.0,6.0,86.0,337.0,1.6,3.0,vegetable
31,13.0,44.0,3.0,1.0,3.0,53.0,166.0,0.8,1.8,fruit

In [62]:
df_high_cal_y = df_high_cal['classification']
df_high_cal_x = df_high_cal.iloc[:, :-1] 
accuracy_score(df_high_cal_y , clf.predict(df_high_cal_x))

1.0

In [64]:
df_low_cal_y = df_low_cal['classification']
df_low_cal_x = df_low_cal.iloc[:, :-1]
accuracy_score(df_low_cal_y, clf.predict(df_low_cal_x))

0.8695652173913043

In [65]:
df_new = pd.read_csv('data/fruits_test.csv')
df_new

,vitamin A %,vitamin C %,calcium %,iron %,magnesium %,calories (per 100g),potassium (mg),protein (g),fiber (g)
0,1.0,154.0,3.0,1.0,4.0,61.0,213.0,1.1,3.0
1,15.0,300.0,2.0,11.0,3.0,20.0,202.0,2.2,2.1
2,0.0,43.0,2.0,3.0,5.0,53.0,151.0,1.1,7.0

In [68]:
clf.predict(df_new)

array(['fruit', 'fruit', 'fruit'], dtype=object)

In [ ]:
# ova e za test proizvodi so specifikacii i vrz baza na toa modelot odlucuva kakov vid e, ovde presudno za prvite dva e vitamin c